# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy project files
COPY package.json package-lock.json* ./
COPY tsconfig.json ./
COPY src ./src
COPY README.md ./

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Expose port if necessary (likely none since MCP uses stdio)
# CMD to start the server
CMD [ "node", "build/index.js" ]
